In [13]:
# import library
import tensorflow as tf

In [14]:
# load datasets
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [15]:
# create the model
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [16]:
# make a sample prediction on the training data
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[ 0.16660246,  1.0130169 , -0.4882297 , -0.54627794, -0.2682268 ,
        -0.02268696, -0.12109585,  0.03527361, -0.10056205, -0.819583  ]],
      dtype=float32)

In [17]:
# get class probabilities from predictions
tf.nn.softmax(predictions).numpy()

array([[0.1165309 , 0.27166533, 0.06054121, 0.05712695, 0.07543921,
        0.09643479, 0.08739675, 0.10218936, 0.08920989, 0.04346566]],
      dtype=float32)

In [18]:
# choose a loss function to train the model with
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [19]:
# view a sample loss from one record
loss_fn(y_train[:1], predictions).numpy()

2.3388882

In [20]:
# compile the model with the loss function and accuract metric
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [21]:
# train the model
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 3s 56us/sample - loss: 0.2922 - accuracy: 0.9147
Epoch 2/5
60000/60000 [==============================] - 3s 46us/sample - loss: 0.1410 - accuracy: 0.9592
Epoch 3/5
60000/60000 [==============================] - 3s 46us/sample - loss: 0.1049 - accuracy: 0.9680
Epoch 4/5
60000/60000 [==============================] - 3s 46us/sample - loss: 0.0865 - accuracy: 0.9730
Epoch 5/5
60000/60000 [==============================] - 3s 47us/sample - loss: 0.0718 - accuracy: 0.9776


In [22]:
# evaluate performance on validation data
model.evaluate(x_test,  y_test, verbose=2)

10000/10000 - 0s - loss: 0.0766 - accuracy: 0.9773


[0.07658484817608259, 0.9773]

In [23]:
# to get predictions in probabilities apply Softmax layer
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [24]:
# predict probabilities
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.1704606e-06, 1.8928047e-08, 2.3592589e-05, 4.6615710e-04,
        3.3151706e-12, 2.0998516e-07, 2.1942711e-13, 9.9946064e-01,
        2.2028198e-07, 4.7929265e-05],
       [6.9976100e-09, 1.0632260e-03, 9.9868041e-01, 2.5264479e-04,
        1.2107988e-14, 2.2349727e-06, 3.0995153e-08, 3.1998365e-13,
        1.4207475e-06, 5.9360676e-12],
       [5.7224376e-08, 9.9951839e-01, 8.6827640e-05, 2.2995739e-05,
        2.8835335e-05, 3.7244426e-06, 3.2277492e-06, 2.0220036e-04,
        1.3359124e-04, 2.4193278e-07],
       [9.9967623e-01, 2.2476103e-09, 6.8233392e-05, 6.3742777e-07,
        9.0493222e-07, 1.0729312e-05, 2.9640913e-05, 1.3190409e-05,
        1.2566466e-07, 2.0037587e-04],
       [1.6951077e-06, 4.2386904e-07, 3.7460452e-06, 4.5316233e-07,
        9.9353242e-01, 1.2894998e-06, 2.2973707e-06, 4.0607987e-04,
        3.2867209e-07, 6.0512796e-03]], dtype=float32)>